create database sell;

DROP TABLE IF EXISTS SYS_USER;
DROP TABLE IF EXISTS SYS_ROLE;
DROP TABLE IF EXISTS SYS_AUTHORITIES;
DROP TABLE IF EXISTS SYS_USER_ROLE;
DROP TABLE IF EXISTS SYS_ROLE_AUTHORITIES;
DROP TABLE IF EXISTS BUSINESS;
DROP TABLE IF EXISTS BUSINESS_USER;
DROP TABLE IF EXISTS CUSTOMER;
DROP TABLE IF EXISTS PRODUCT;

CREATE TABLE SYS_USER
(
    ID INT(10) ZEROFILL AUTO_INCREMENT PRIMARY KEY,
    LOGIN_NAME VARCHAR(50) NOT NULL,
    USER_PASSWORD VARCHAR(50) NOT NULL,
    USER_NAME VARCHAR(20),
    ENABLED   VARCHAR(1) DEFAULT '1' NOT NULL,
    MOBILE VARCHAR(20),
    WECHAT VARCHAR(50)
);

ALTER TABLE SYS_USER COMMENT='用户表';
ALTER table SYS_USER MODIFY 'LOGIN_NAME' COMMENT '登录账号';
ALTER table SYS_USER MODIFY 'USER_PASSWORD' COMMENT '用户密码';
ALTER table SYS_USER MODIFY 'USER_NAME' COMMENT '用户姓名';
ALTER table SYS_USER MODIFY 'ENABLED' COMMENT '是否启用 1:启用 0:停用';
ALTER table SYS_USER MODIFY 'MOBILE' COMMENT '手机号';
ALTER table SYS_USER MODIFY 'WECHAT' COMMENT '微信号';


CREATE TABLE SYS_ROLE
(
    ID INT(10) ZEROFILL AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL,
    DESCRIPTION VARCHAR(50) NOT NULL, 
    ENABLED   VARCHAR(1) DEFAULT '1' NOT NULL 
);

CREATE TABLE SYS_AUTHORITIES
(
    ID INT(10) ZEROFILL AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL, 
    DESCRIPTION VARCHAR(50) NOT NULL, 
    PERMISSION VARCHAR(50), 
    ENABLED   VARCHAR(1) DEFAULT '1' NOT NULL 
);


CREATE TABLE SYS_USER_ROLE
(
  ID      INT(10) ZEROFILL AUTO_INCREMENT PRIMARY KEY,
  USER_ID INT(10) NOT NULL,
  ROLE_ID INT(10) NOT NULL
);

CREATE TABLE SYS_ROLE_AUTHORITIES
(
  ID      INT(10) ZEROFILL AUTO_INCREMENT PRIMARY KEY,
  ROLE_ID INT(10) NOT NULL,
  AUTH_ID INT(10) NOT NULL
);

CREATE TABLE DEALERS
(
    ID INT(10) ZEROFILL AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL, 
    DESCRIPTION VARCHAR(20), 
    CODE VARCHAR(100),
    ENABLED   VARCHAR(1) DEFAULT '1' NOT NULL, 
    PHONE VARCHAR(20),
    ADDRESS VARCHAR(200) 
);

CREATE TABLE DEALERS_USER
(
  ID      INT(10) ZEROFILL AUTO_INCREMENT PRIMARY KEY,
  DEALERS_ID INT(10) NOT NULL,
  USER_ID INT(10) NOT NULL
);


CREATE TABLE CUSTOMER
(
    ID INT(10) ZEROFILL AUTO_INCREMENT PRIMARY KEY,
    WECHAT VARCHAR(100) not null, 
    NICK VARCHAR(50) not null, 
    BUSINESS_ID INT(10) 
);

CREATE TABLE PRODUCT
(
    ID INT(10) ZEROFILL AUTO_INCREMENT PRIMARY KEY,
    PRODUCT_ID VARCHAR(100) not null, 
    PRODUCT_NAME VARCHAR(200) not null, 
    PRODUCT_PRICE DOUBLE(10) not null, 
    DISCOUNT DOUBLE(10) not null 
);
